content overview: add tabs for models and display all objects ordered by date created
DDMAL/CantusDB pull request #908
Opened 2023-08-01 17:25 UTC by lucasmarchd01

In this PR, modifications are made to the content-overview page. Previously, this page would only display the last 50 updated objects in our database. The way this information was fetched was inefficient, making it impossible to scale to use all the objects in our database without affecting the page loading time. The solution implements tabs at the top of the page that represent the relevant models in our database. When the user clicks on one of these tabs, we will display all of the objects corresponding to this model ordered by "-date_created". The user can now paginate through all of these objects with 100 objects per page. Fixes #896 

![image](https://github.com/DDMAL/CantusDB/assets/71031342/a0f3f9eb-aa58-47e1-a030-f9a68b760a28)

2023-08-01 18:53 UTC, jacobdgm requested changes
This looks good! I left one comment to check that `Century` models haven't been overlooked, and one suggesting a possible simplification to the code.

One other thing: do any tests need to be updated to match these changes? If not, maybe now is a good time to write a good set of tests for this view.

2023-08-01 18:53 UTC, jacobdgm commented on django/cantusdb_project/main_app/views/views.py
> +        Source,
Are we sure we don't want to include Century in this list?

2023-08-01 18:53 UTC, jacobdgm commented on django/cantusdb_project/main_app/templates/content_overview.html
> +                                {{ object.last_updated_by }}
Maybe it would be clearer to just put `None` rather than `{{ object.last_updated_by }}` (since we already know it's `None`)

2023-08-01 20:37 UTC, lucasmarchd01 commented on django/cantusdb_project/main_app/views/views.py
> +        Source,
Century is still included, I just changed the ordering of this list and Century was moved further down.

2023-08-01 20:38 UTC, lucasmarchd01 commented on django/cantusdb_project/main_app/templates/content_overview.html
> +                                {{ object.last_updated_by }}
Makes sense!

2023-08-01 20:40 UTC, lucasmarchd01 commented
> One other thing: do any tests need to be updated to match these changes? If not, maybe now is a good time to write a 
> good set of tests for this view.
Thanks for the suggestion, will do.

2023-08-02 17:08 UTC, jacobdgm approved these changes

2023-08-02 17:08 UTC, merged