Create postgres backup scripts and set up cron jobs
DDMAL/CantusDB pull request #933
Opened 2023-08-03 17:34 UTC by jackyyzhang03

Resolves #395. 

Created database backup scripts that are run as cron jobs inside the `postgres` container. The backups are stored in a Docker volume called `postgres_backups`, with separate directories for daily, weekly, and monthly backups. The scripts are currently set up to keep 7 days of daily backups, 30 days of weekly backups, and 365 days of monthly backups.

2023-08-03 18:48 UTC, jacobdgm commented on postgres/scripts/monthly.sh
> +# It then deletes any montly backups older than 7 days.
this comment is incorrect - it deletes any monthly backups older than a year.

2023-08-04 15:56 UTC, jacobdgm requested changes

2023-08-04 15:56 UTC, jacobdgm commented on cron/postgres/monthly.sh
> +# This script creates a compressed SQL dump of the database in the /home/ubuntu/backups/postgres/montly directory.
Here, and elsewhere in this file, "monthly" rather than "montly"

2023-08-04 16:00 UTC, jacobdgm commented
Also, would it make sense to create yearly backups that we keep indefinitely?

I'm also thinking of where certbot things will fit into this: does it make sense to address #870 within this PR, or to merge this PR and create a new one for certbot? i understand this needs to be run a little bit more often than yearly (something like every 9 months?)

2023-08-04 16:09 UTC, jackyyzhang03 commented
>Also, would it make sense to create yearly backups that we keep indefinitely?

I added another job to keep yearly backups for a decade.

>I'm also thinking of where certbot things will fit into this

Not sure, though if you think it is a good idea, we can do it in this PR along with #740 and maybe #877?

2023-08-04 17:21 UTC, jacobdgm requested changes
This most recent round of changes looks quite good! I left just one comment with a requested change. Thanks for taking the time to set this up!

2023-08-04 17:21 UTC, jacobdgm commented on cron/cron.txt
> +25      4       1       *       *       bash /home/ubuntu/code/CantusDB/cron/management/manage.sh populate_next_chant_fields
Good thought to ensure these don't all run at the same time! Can we run `populate_next_chant_fields` before `populate_is_last_chant_in_feast` (we need up-to-date data on which chants follow each other before we can accurately calculate which chants end feasts)?

2023-08-08 13:44 UTC, jacobdgm commented on cron/cron.txt
> +40      4       1       *       *       bash /home/ubuntu/code/CantusDB/cron/management/manage.sh populate_is_last_chant_in_feast; bash /home/ubuntu/code/CantusDB/cron/management/manage.sh populate_n
This appears to be back to calculating `is_last_chant_in_feast` before calculating `next_chant`? `is_last_chant_in_feast` depends on `next_chant`.

2023-08-08 17:20 UTC, jacobdgm approved these changes
To me, this looks like it does what we need it to! I'll wait before merging until @kqct has checked this over to verify that the certbot setup is correct.

2023-08-08 17:45 UTC, meow10811 commented
The certbot setup looks correct, but I'd caution that SSL certificates expire in 90 days -- maybe run the renewal script every 2 months instead of every 6?

2023-08-08 17:46 UTC, jacobdgm commented
> maybe run the renewal script every 2 months instead of every 6?

@jackyyzhang03

2023-08-08 19:31 UTC, kqct approved these changes

2023-08-08 19:41 UTC, merged

2023-08-09 07:40 UTC, ahankinson commented
Just a note to say that you should run the certbot script much more frequently than that. You can run it every night, or at least once a week. If the certificate is not due for renewal then it will bail and nothing will happen, but if you only run it every two months and some transient error happens (certbot servers are down for maintenance; your servers have a network glitch) then you've lost your window and your certificate will expire.

There's no downside to running it daily or weekly.

2023-08-09 12:58 UTC, jacobdgm commented
Thanks, @ahankinson - done! #956